-- Insert sample candidate data for testing
-- This will create a candidate with ID 1 for testing the /candidates/1 endpoint

INSERT INTO candidates (
    full_name, 
    email, 
    phone_number, 
    date_of_birth, 
    gender, 
    address, 
    city, 
    state, 
    pincode, 
    password, 
    course, 
    joining_date, 
    fees_transaction_number, 
    job_admission,
    profile_title,
    current_job_status,
    total_experience_years,
    total_experience_months,
    current_employer,
    current_job_title,
    primary_skills,
    secondary_skills,
    skill_proficiency_level,
    certifications,
    highest_qualification,
    specialization,
    university,
    year_of_passing,
    grades,
    preferred_job_type,
    preferred_industry,
    preferred_roles,
    expected_salary,
    work_mode_preference,
    notice_period,
    linkedin_url,
    portfolio_url,
    languages,
    work_authorization,
    status,
    priority,
    created_at,
    updated_at
) VALUES (
    'John Smith',
    'john.smith@email.com',
    '9876543210',
    '1990-05-15',
    'male',
    '123 Main St, San Francisco, CA 94102',
    'San Francisco',
    'California',
    '94102',
    '$2b$12$hashed_password_example', -- This is a placeholder hashed password
    'web-development',
    '2024-01-15',
    'TXN123456',
    false,
    'Senior Frontend Developer',
    'employed',
    5,
    3,
    'TechCorp Inc.',
    'Frontend Developer',
    '["React", "TypeScript", "JavaScript", "CSS", "HTML"]',
    '["Node.js", "GraphQL", "Redux"]',
    'advanced',
    '["AWS Certified Developer", "React Certification"]',
    'Bachelor of Science',
    'Computer Science',
    'Stanford University',
    2018,
    '3.8/4.0',
    'full-time',
    'Technology',
    '["Senior Frontend Developer", "Frontend Lead", "UI Developer"]',
    '$130,000 - $150,000',
    'hybrid',
    '2 weeks',
    'https://linkedin.com/in/johnsmith',
    'https://johnsmith.dev',
    '[{"language": "English", "proficiency": "native"}, {"language": "Spanish", "proficiency": "conversational"}]',
    'US Citizen',
    'pending',
    'high',
    NOW(),
    NOW()
);

-- Verify the insertion
SELECT id, full_name, email, city, state, status 
FROM candidates 
WHERE id = 1;
